import { addDays, subDays } from 'date-fns';

// Type for sales invoice data
export interface SalesInvoiceData {
  id: string;
  invoiceNumber: string;
  store: string;
  source: string; // POS system
  date: Date;
  status: string;
  subtotal: number;
  vatRate: number;
  vat: number;
  total: number;
  paymentMethod: string;
  archived: boolean;
  deleted: boolean;
  lineItems: SalesLineItem[];
  requiresJournaling: boolean;
  journalEntries?: JournalEntry[];
  notes?: string;
  previewUrl?: string;
}

export interface SalesLineItem {
  id: string;
  description: string;
  category: string;
  quantity: number;
  price: number;
  subtotal: number;
  vatRate: number;
  vat: number;
  total: number;
}

export interface JournalEntry {
  id: string;
  account: string;
  description: string;
  debit: number;
  credit: number;
}

// Generate sales data
export const salesInvoices: SalesInvoiceData[] = [
  {
    id: "s001",
    invoiceNumber: "DOM-POS-001",
    store: "Dominos",
    source: "Dominos POS",
    date: subDays(new Date(), 2),
    status: "Processed",
    subtotal: 1250.75,
    vatRate: 20,
    vat: 250.15,
    total: 1500.90,
    paymentMethod: "Mixed",
    archived: false,
    deleted: false,
    lineItems: [
      {
        id: "item001",
        description: "Delivered Orders",
        category: "Food",
        quantity: 35,
        price: 19.99,
        subtotal: 699.65,
        vatRate: 20,
        vat: 139.93,
        total: 839.58,
      },
      {
        id: "item002",
        description: "Collection Orders",
        category: "Food",
        quantity: 28,
        price: 18.75,
        subtotal: 525.00,
        vatRate: 20,
        vat: 105.00,
        total: 630.00,
      },
      {
        id: "item003",
        description: "Drinks",
        category: "Beverages",
        quantity: 17,
        price: 1.50,
        subtotal: 25.50,
        vatRate: 20,
        vat: 5.10,
        total: 30.60,
      },
    ],
    requiresJournaling: true,
    journalEntries: [
      {
        id: "je001",
        account: "4000",
        description: "Sales Revenue",
        debit: 0,
        credit: 1250.75,
      },
      {
        id: "je002",
        account: "2200",
        description: "VAT Payable",
        debit: 0,
        credit: 250.15,
      },
      {
        id: "je003",
        account: "1000",
        description: "Cash",
        debit: 750.45,
        credit: 0,
      },
      {
        id: "je004",
        account: "1200",
        description: "Credit Cards",
        debit: 750.45,
        credit: 0,
      },
    ],
    notes: "Daily sales report from Domino's POS system",
    previewUrl: "sales-receipt-1.pdf",
  },
  {
    id: "s002",
    invoiceNumber: "UBER-123456",
    store: "Dominos",
    source: "UberEats",
    date: subDays(new Date(), 1),
    status: "Pending Review",
    subtotal: 742.50,
    vatRate: 20,
    vat: 148.50,
    total: 891.00,
    paymentMethod: "Online Payment",
    archived: false,
    deleted: false,
    lineItems: [
      {
        id: "item001",
        description: "Food Orders",
        category: "Food",
        quantity: 23,
        price: 25.50,
        subtotal: 586.50,
        vatRate: 20,
        vat: 117.30,
        total: 703.80,
      },
      {
        id: "item002",
        description: "Delivery Fees",
        category: "Service",
        quantity: 23,
        price: 3.49,
        subtotal: 80.27,
        vatRate: 20,
        vat: 16.05,
        total: 96.32,
      },
      {
        id: "item003",
        description: "Uber Service Fee",
        category: "Commission",
        quantity: 1,
        price: -148.50,
        subtotal: -148.50,
        vatRate: 20,
        vat: -29.70,
        total: -178.20,
      },
    ],
    requiresJournaling: true,
    notes: "Weekly settlement from UberEats",
    previewUrl: "sales-receipt-2.pdf",
  },
  {
    id: "s003",
    invoiceNumber: "JE-123-456-789",
    store: "Dominos",
    source: "JustEat",
    date: subDays(new Date(), 3),
    status: "Processed",
    subtotal: 865.25,
    vatRate: 20,
    vat: 173.05,
    total: 1038.30,
    paymentMethod: "Bank Transfer",
    archived: false,
    deleted: false,
    lineItems: [
      {
        id: "item001",
        description: "JustEat Orders",
        category: "Food",
        quantity: 27,
        price: 32.05,
        subtotal: 865.25,
        vatRate: 20,
        vat: 173.05,
        total: 1038.30,
      },
      {
        id: "item002",
        description: "JustEat Commission",
        category: "Commission",
        quantity: 1,
        price: -129.79,
        subtotal: -129.79,
        vatRate: 20,
        vat: -25.96,
        total: -155.75,
      },
    ],
    requiresJournaling: true,
    notes: "Weekly settlement from JustEat platform",
    previewUrl: "sales-receipt-3.pdf",
  },
  {
    id: "s004",
    invoiceNumber: "DOM-POS-002",
    store: "GDK",
    source: "GDK POS",
    date: subDays(new Date(), 5),
    status: "Processed",
    subtotal: 1850.30,
    vatRate: 20,
    vat: 370.06,
    total: 2220.36,
    paymentMethod: "Mixed",
    archived: false,
    deleted: false,
    lineItems: [
      {
        id: "item001",
        description: "In-store Sales",
        category: "Food",
        quantity: 1,
        price: 1420.50,
        subtotal: 1420.50,
        vatRate: 20,
        vat: 284.10,
        total: 1704.60,
      },
      {
        id: "item002",
        description: "Takeaway Orders",
        category: "Food",
        quantity: 1,
        price: 429.80,
        subtotal: 429.80,
        vatRate: 20,
        vat: 85.96,
        total: 515.76,
      },
    ],
    requiresJournaling: true,
    notes: "Daily sales report from German Doner Kebab POS",
    previewUrl: "sales-receipt-4.pdf",
  },
  {
    id: "s005",
    invoiceNumber: "DELIVEROO-98765",
    store: "GDK",
    source: "Deliveroo",
    date: subDays(new Date(), 6),
    status: "AI Processed",
    subtotal: 562.10,
    vatRate: 20,
    vat: 112.42,
    total: 674.52,
    paymentMethod: "Online Payment",
    archived: false,
    deleted: false,
    lineItems: [
      {
        id: "item001",
        description: "Deliveroo Orders",
        category: "Food",
        quantity: 19,
        price: 29.58,
        subtotal: 562.10,
        vatRate: 20,
        vat: 112.42,
        total: 674.52,
      },
      {
        id: "item002",
        description: "Deliveroo Commission",
        category: "Commission",
        quantity: 1,
        price: -112.42,
        subtotal: -112.42,
        vatRate: 20,
        vat: -22.48,
        total: -134.90,
      },
    ],
    requiresJournaling: true,
    notes: "Weekly settlement from Deliveroo",
    previewUrl: "sales-receipt-5.pdf",
  },
  {
    id: "s006",
    invoiceNumber: "COSTA-POS-001",
    store: "Costa",
    source: "Costa POS",
    date: subDays(new Date(), 4),
    status: "Processed",
    subtotal: 1475.85,
    vatRate: 20,
    vat: 295.17,
    total: 1771.02,
    paymentMethod: "Mixed",
    archived: false,
    deleted: false,
    lineItems: [
      {
        id: "item001",
        description: "Hot Drinks",
        category: "Beverages",
        quantity: 187,
        price: 3.25,
        subtotal: 607.75,
        vatRate: 20,
        vat: 121.55,
        total: 729.30,
      },
      {
        id: "item002",
        description: "Cold Drinks",
        category: "Beverages",
        quantity: 95,
        price: 3.75,
        subtotal: 356.25,
        vatRate: 20,
        vat: 71.25,
        total: 427.50,
      },
      {
        id: "item003",
        description: "Food Items",
        category: "Food",
        quantity: 92,
        price: 5.56,
        subtotal: 511.85,
        vatRate: 20,
        vat: 102.37,
        total: 614.22,
      },
    ],
    requiresJournaling: true,
    notes: "Daily sales report from Costa Coffee POS",
    previewUrl: "sales-receipt-6.pdf",
  },
  {
    id: "s007",
    invoiceNumber: "JE-234-567-890",
    store: "Costa",
    source: "JustEat",
    date: subDays(new Date(), 7),
    status: "Needs Attention",
    subtotal: 342.75,
    vatRate: 20,
    vat: 68.55,
    total: 411.30,
    paymentMethod: "Bank Transfer",
    archived: false,
    deleted: false,
    lineItems: [
      {
        id: "item001",
        description: "JustEat Orders",
        category: "Mixed",
        quantity: 18,
        price: 19.04,
        subtotal: 342.75,
        vatRate: 20,
        vat: 68.55,
        total: 411.30,
      },
      {
        id: "item002",
        description: "JustEat Commission",
        category: "Commission",
        quantity: 1,
        price: -58.26,
        subtotal: -58.26,
        vatRate: 20,
        vat: -11.65,
        total: -69.91,
      },
    ],
    requiresJournaling: true,
    notes: "Weekly settlement from JustEat platform - discrepancy found",
    previewUrl: "sales-receipt-7.pdf",
  },
  {
    id: "s008",
    invoiceNumber: "DOM-POS-003",
    store: "Dominos",
    source: "Dominos POS",
    date: addDays(new Date(), 1),
    status: "Draft",
    subtotal: 1320.45,
    vatRate: 20,
    vat: 264.09,
    total: 1584.54,
    paymentMethod: "Mixed",
    archived: false,
    deleted: false,
    lineItems: [
      {
        id: "item001",
        description: "Delivered Orders",
        category: "Food",
        quantity: 37,
        price: 20.55,
        subtotal: 760.35,
        vatRate: 20,
        vat: 152.07,
        total: 912.42,
      },
      {
        id: "item002",
        description: "Collection Orders",
        category: "Food",
        quantity: 30,
        price: 18.67,
        subtotal: 560.10,
        vatRate: 20,
        vat: 112.02,
        total: 672.12,
      },
    ],
    requiresJournaling: false,
    notes: "Draft sales report - pending end of day confirmation",
    previewUrl: "sales-receipt-8.pdf",
  },
  {
    id: "s009",
    invoiceNumber: "UBER-234567",
    store: "GDK",
    source: "UberEats",
    date: subDays(new Date(), 10),
    status: "Processed",
    subtotal: 682.35,
    vatRate: 20,
    vat: 136.47,
    total: 818.82,
    paymentMethod: "Online Payment",
    archived: true,
    deleted: false,
    lineItems: [
      {
        id: "item001",
        description: "Food Orders",
        category: "Food",
        quantity: 21,
        price: 32.49,
        subtotal: 682.35,
        vatRate: 20,
        vat: 136.47,
        total: 818.82,
      },
      {
        id: "item002",
        description: "Uber Service Fee",
        category: "Commission",
        quantity: 1,
        price: -136.47,
        subtotal: -136.47,
        vatRate: 20,
        vat: -27.29,
        total: -163.76,
      },
    ],
    requiresJournaling: true,
    notes: "Weekly settlement from UberEats - archived after processing",
    previewUrl: "sales-receipt-9.pdf",
  },
  {
    id: "s010",
    invoiceNumber: "DEL-ERR-123",
    store: "Costa",
    source: "Deliveroo",
    date: subDays(new Date(), 12),
    status: "Error",
    subtotal: 425.30,
    vatRate: 20,
    vat: 85.06,
    total: 510.36,
    paymentMethod: "Unknown",
    archived: false,
    deleted: true,
    lineItems: [
      {
        id: "item001",
        description: "Error Report",
        category: "Unknown",
        quantity: 1,
        price: 425.30,
        subtotal: 425.30,
        vatRate: 20,
        vat: 85.06,
        total: 510.36,
      },
    ],
    requiresJournaling: false,
    notes: "Erroneous report - deleted after verification",
    previewUrl: "sales-receipt-10.pdf",
  }
]; 