import { subDays } from 'date-fns';
import { SalesInvoiceData } from './components/types';

// Generate enhanced sales data with AI processing features
export const salesInvoices: SalesInvoiceData[] = [
  {
    id: "s001",
    invoiceNumber: "DOM-POS-001",
    store: "Dominos",
    source: "Dominos POS",
    date: subDays(new Date(), 2),
    status: "Processed",
    subtotal: 1250.75,
    vatRate: 20,
    vat: 250.15,
    total: 1500.90,
    paymentMethod: "Mixed",
    archived: false,
    deleted: false,
    confidence: 95,
    lastProcessed: subDays(new Date(), 2),
    uploadedFile: {
      id: "file001",
      name: "dominos_daily_sales.pdf",
      type: "pdf",
      url: "/uploads/dominos_daily_sales.pdf",
      size: 524288,
      uploadDate: subDays(new Date(), 2)
    },
    aiExtractedData: {
      invoiceNumber: "DOM-POS-001",
      supplier: "Dominos Pizza UK Ltd",
      supplierAddress: "1 Lansdowne Gate, Croydon CR0 2BX, UK",
      invoiceDate: subDays(new Date(), 2),
      totalAmount: 1500.90,
      subtotalAmount: 1250.75,
      vatAmount: 250.15,
      currency: "GBP",
      accountCode: "4000",
      storeLocation: "Dominos - Main Street"
    },
    supplierInfo: {
      id: "sup001",
      name: "Dominos Pizza UK Ltd",
      address: "1 Lansdowne Gate, Croydon CR0 2BX, UK",
      taxId: "GB123456789",
      accountCode: "4000",
      paymentTerms: "NET 30",
      isNew: false,
      confidence: 98
    },
    lineItems: [
      {
        id: "item001",
        description: "Delivered Orders",
        category: "Food Sales",
        quantity: 35,
        price: 19.99,
        subtotal: 699.65,
        vatRate: 20,
        vat: 139.93,
        total: 839.58,
      },
      {
        id: "item002",
        description: "Collection Orders",
        category: "Food Sales",
        quantity: 28,
        price: 18.75,
        subtotal: 525.00,
        vatRate: 20,
        vat: 105.00,
        total: 630.00,
      },
      {
        id: "item003",
        description: "Drinks & Sides",
        category: "Beverages",
        quantity: 17,
        price: 1.50,
        subtotal: 25.50,
        vatRate: 20,
        vat: 5.10,
        total: 30.60,
      },
    ],
    requiresJournaling: true,
    journalEntries: [
      {
        id: "je001",
        account: "4000",
        description: "Sales Revenue",
        debit: 0,
        credit: 1250.75,
      },
      {
        id: "je002",
        account: "2200",
        description: "VAT Payable",
        debit: 0,
        credit: 250.15,
      },
      {
        id: "je003",
        account: "1000",
        description: "Cash",
        debit: 750.45,
        credit: 0,
      },
      {
        id: "je004",
        account: "1200",
        description: "Credit Cards",
        debit: 750.45,
        credit: 0,
      },
    ],
    notes: "Daily sales report from Domino's POS system - AI processed successfully",
    previewUrl: "sales-receipt-1.pdf",
  },
  {
    id: "s002",
    invoiceNumber: "UBER-123456",
    store: "Dominos",
    source: "UberEats",
    date: subDays(new Date(), 1),
    status: "Review",
    subtotal: 742.50,
    vatRate: 20,
    vat: 148.50,
    total: 891.00,
    paymentMethod: "Online Payment",
    archived: false,
    deleted: false,
    confidence: 67,
    lastProcessed: subDays(new Date(), 1),
    uploadedFile: {
      id: "file002",
      name: "uber_eats_settlement.csv",
      type: "csv",
      url: "/uploads/uber_eats_settlement.csv",
      size: 15360,
      uploadDate: subDays(new Date(), 1)
    },
    aiExtractedData: {
      invoiceNumber: "UBER-123456", 
      supplier: "Uber Technologies Inc",
      supplierAddress: "Incomplete address data",
      invoiceDate: subDays(new Date(), 1),
      totalAmount: 891.00,
      subtotalAmount: 742.50,
      vatAmount: 148.50,
      currency: "GBP",
      storeLocation: "Unknown store location"
    },
    supplierInfo: {
      name: "Uber Technologies Inc",
      address: "Incomplete - requires verification",
      isNew: false,
      confidence: 45
    },
    reviewErrors: [
      {
        id: "err001",
        type: "incomplete_address",
        title: "Incomplete Supplier Address",
        description: "The supplier address is missing postal code and full street details",
        severity: "medium",
        suggestedAction: "Verify and complete the supplier address in settings",
        fieldPath: "supplierInfo.address",
        confidence: 65
      },
      {
        id: "err002",
        type: "unknown_store",
        title: "Store Location Not Identified",
        description: "AI couldn't determine which store this settlement applies to",
        severity: "high",
        suggestedAction: "Assign this invoice to the correct store location",
        fieldPath: "store",
        confidence: 35
      }
    ],
    lineItems: [
      {
        id: "item001",
        description: "Food Orders",
        category: "Food Sales",
        quantity: 23,
        price: 25.50,
        subtotal: 586.50,
        vatRate: 20,
        vat: 117.30,
        total: 703.80,
      },
      {
        id: "item002",
        description: "Delivery Fees",
        category: "Service Revenue",
        quantity: 23,
        price: 3.49,
        subtotal: 80.27,
        vatRate: 20,
        vat: 16.05,
        total: 96.32,
      },
      {
        id: "item003",
        description: "Uber Commission",
        category: "Commission Expense",
        quantity: 1,
        price: -148.50,
        subtotal: -148.50,
        vatRate: 20,
        vat: -29.70,
        total: -178.20,
      },
    ],
    requiresJournaling: true,
    notes: "Weekly settlement from UberEats - requires review",
    previewUrl: "sales-receipt-2.pdf",
  },
  {
    id: "s003",
    invoiceNumber: "JE-789-123",
    store: "Unknown",
    source: "JustEat",
    date: new Date(),
    status: "Processing",
    subtotal: 0,
    vatRate: 20,
    vat: 0,
    total: 0,
    paymentMethod: "Unknown",
    archived: false,
    deleted: false,
    confidence: 15,
    lastProcessed: new Date(),
    uploadedFile: {
      id: "file003",
      name: "justeat_invoice_blurry.pdf",
      type: "pdf",
      url: "/uploads/justeat_invoice_blurry.pdf",
      size: 1048576,
      uploadDate: new Date()
    },
    aiExtractedData: {
      invoiceNumber: "JE-789-123",
      supplier: "Just Eat Holdings Ltd",
      invoiceDate: new Date(),
      currency: "GBP"
    },
    supplierInfo: {
      name: "Just Eat Holdings Ltd",
      isNew: false,
      confidence: 78
    },
    lineItems: [],
    requiresJournaling: false,
    notes: "Currently being processed by AI - low quality scan detected",
  },
  {
    id: "s004",
    invoiceNumber: "SAV-001-2025",
    store: "Savills",
    source: "Manual Upload",
    date: subDays(new Date(), 5),
    status: "Review",
    subtotal: 9000.00,
    vatRate: 20,
    vat: 1800.00,
    total: 10800.00,
    paymentMethod: "Bank Transfer",
    archived: false,
    deleted: false,
    confidence: 42,
    lastProcessed: subDays(new Date(), 5),
    uploadedFile: {
      id: "file004",
      name: "savills_property_services.pdf",
      type: "pdf",
      url: "/uploads/savills_property_services.pdf",
      size: 782000,
      uploadDate: subDays(new Date(), 5)
    },
    aiExtractedData: {
      invoiceNumber: "SAV-001-2025",
      supplier: "Savills Property Management Ltd",
      supplierAddress: "33 Margaret Street, London W1G 0JD",
      invoiceDate: subDays(new Date(), 5),
      totalAmount: 10800.00,
      subtotalAmount: 9000.00,
      vatAmount: 1800.00,
      currency: "GBP",
      reference: "Property maintenance services"
    },
    supplierInfo: {
      name: "Savills Property Management Ltd",
      address: "33 Margaret Street, London W1G 0JD",
      taxId: "GB987654321",
      isNew: true,
      confidence: 85
    },
    reviewErrors: [
      {
        id: "err003",
        type: "new_supplier",
        title: "New Supplier Detected",
        description: "This supplier is not in your system. AI suggests adding 'Savills Property Management Ltd' as a new supplier.",
        severity: "medium",
        suggestedAction: "Review supplier details and confirm addition to your supplier database",
        fieldPath: "supplierInfo",
        confidence: 85
      },
      {
        id: "err004", 
        type: "unknown_account_code",
        title: "Account Code Assignment Required",
        description: "AI couldn't determine the appropriate account code for property services",
        severity: "high",
        suggestedAction: "Assign appropriate account code (suggested: 7200 - Property Expenses)",
        fieldPath: "accountCode",
        confidence: 20
      }
    ],
    lineItems: [
      {
        id: "item001",
        description: "Property Management Services",
        category: "Professional Services",
        quantity: 1,
        price: 9000.00,
        subtotal: 9000.00,
        vatRate: 20,
        vat: 1800.00,
        total: 10800.00,
      }
    ],
    requiresJournaling: true,
    notes: "New supplier - requires approval before processing",
  },
  {
    id: "s005",
    invoiceNumber: "COSTA-DUP-2025",
    store: "Costa Coffee",
    source: "Email Upload",
    date: subDays(new Date(), 1),
    status: "Review",
    subtotal: 2500.00,
    vatRate: 20,
    vat: 500.00,
    total: 3000.00,
    paymentMethod: "Direct Debit",
    archived: false,
    deleted: false,
    confidence: 25,
    lastProcessed: subDays(new Date(), 1),
    uploadedFile: {
      id: "file005",
      name: "costa_supplies_duplicate.pdf",
      type: "pdf",
      url: "/uploads/costa_supplies_duplicate.pdf",
      size: 445000,
      uploadDate: subDays(new Date(), 1)
    },
    aiExtractedData: {
      invoiceNumber: "COSTA-DUP-2025",
      supplier: "Costa Coffee Limited",
      supplierAddress: "Whitbread Court, Houghton Hall Business Park, Dunstable LU5 5XE",
      invoiceDate: subDays(new Date(), 1),
      totalAmount: 3000.00,
      subtotalAmount: 2500.00,
      vatAmount: 500.00,
      currency: "GBP"
    },
    supplierInfo: {
      id: "sup002",
      name: "Costa Coffee Limited",
      address: "Whitbread Court, Houghton Hall Business Park, Dunstable LU5 5XE",
      taxId: "GB555666777",
      accountCode: "5000",
      isNew: false,
      confidence: 95
    },
    reviewErrors: [
      {
        id: "err005",
        type: "duplicate_invoice",
        title: "Potential Duplicate Invoice",
        description: "This invoice may be a duplicate of invoice COSTA-001-2025 processed last week",
        severity: "critical",
        suggestedAction: "Review for duplicate payment - compare with existing records",
        confidence: 78
      },
      {
        id: "err006",
        type: "validation_error",
        title: "Amount Validation Issue",
        description: "The invoice total doesn't match the sum of line items",
        severity: "high",
        suggestedAction: "Verify invoice calculations and correct any discrepancies",
        fieldPath: "total",
        confidence: 92
      }
    ],
    lineItems: [
      {
        id: "item001",
        description: "Coffee Supplies",
        category: "Inventory",
        quantity: 50,
        price: 45.00,
        subtotal: 2250.00,
        vatRate: 20,
        vat: 450.00,
        total: 2700.00,
      },
      {
        id: "item002",
        description: "Equipment Rental",
        category: "Equipment",
        quantity: 1,
        price: 250.00,
        subtotal: 250.00,
        vatRate: 20,
        vat: 50.00,
        total: 300.00,
      }
    ],
    requiresJournaling: true,
    notes: "Flagged as potential duplicate - requires manual verification",
  },
  {
    id: "s006",
    invoiceNumber: "POST-001-2025",
    store: "All Locations",
    source: "Xero Integration",
    date: subDays(new Date(), 7),
    status: "Posted",
    subtotal: 5000.00,
    vatRate: 20,
    vat: 1000.00,
    total: 6000.00,
    paymentMethod: "Bank Transfer",
    archived: false,
    deleted: false,
    confidence: 98,
    lastProcessed: subDays(new Date(), 7),
    uploadedFile: {
      id: "file006",
      name: "marketing_services_final.pdf",
      type: "pdf",
      url: "/uploads/marketing_services_final.pdf",
      size: 892000,
      uploadDate: subDays(new Date(), 7)
    },
    aiExtractedData: {
      invoiceNumber: "POST-001-2025",
      supplier: "Digital Marketing Solutions Ltd",
      supplierAddress: "Tower Bridge Business Centre, 46-48 East Smithfield, London E1W 1AW",
      invoiceDate: subDays(new Date(), 7),
      totalAmount: 6000.00,
      subtotalAmount: 5000.00,
      vatAmount: 1000.00,
      currency: "GBP",
      accountCode: "6200",
      reference: "Monthly marketing campaign"
    },
    supplierInfo: {
      id: "sup003",
      name: "Digital Marketing Solutions Ltd",
      address: "Tower Bridge Business Centre, 46-48 East Smithfield, London E1W 1AW",
      taxId: "GB444555666",
      accountCode: "6200",
      paymentTerms: "NET 15",
      isNew: false,
      confidence: 98
    },
    lineItems: [
      {
        id: "item001",
        description: "Digital Marketing Campaign",
        category: "Marketing",
        quantity: 1,
        price: 4000.00,
        subtotal: 4000.00,
        vatRate: 20,
        vat: 800.00,
        total: 4800.00,
      },
      {
        id: "item002",
        description: "Social Media Management",
        category: "Marketing",
        quantity: 1,
        price: 1000.00,
        subtotal: 1000.00,
        vatRate: 20,
        vat: 200.00,
        total: 1200.00,
      }
    ],
    requiresJournaling: true,
    journalEntries: [
      {
        id: "je010",
        account: "6200",
        description: "Marketing Expenses",
        debit: 5000.00,
        credit: 0,
      },
      {
        id: "je011",
        account: "1210",
        description: "VAT Reclaimable",
        debit: 1000.00,
        credit: 0,
      },
      {
        id: "je012",
        account: "2100",
        description: "Accounts Payable",
        debit: 0,
        credit: 6000.00,
      },
    ],
    notes: "Successfully processed and posted to Xero",
  }
];

export default salesInvoices; 