import { SalesInvoiceData } from "./components/types";

/**
 * Real invoice data extracted from uploaded invoice examples.
 * Each record includes AI-processed metadata and review errors for human validation.
 */

export const salesInvoices: SalesInvoiceData[] = [
  // REVIEW STATUS INVOICES
  {
    id: "inv-001",
    invoiceNumber: "9106602792",
    company: "Franchise Holdings Ltd",
    store: "Lancaster",
    source: "Email Upload",
    date: new Date("2025-04-08"),
    dueDate: new Date("2025-05-24"),
    accountCode: "5000",
    status: "Review",
    subtotal: 463.91,
    vatRate: 20,
    vat: 92.78,
    total: 556.69,
    paymentMethod: "Bank Transfer",
    archived: false,
    deleted: false,
    documentType: "Invoice",
    uploadedFile: {
      id: "file001",
      name: "Coca-Cola_Europacific_Partners_2025-04-08_556.69.pdf",
      type: "pdf",
      url: "/invoice-previews/InvoiceExamples/Coca-Cola_Europacific_Partners_2025-04-08_556.69.pdf",
      size: 81920,
      uploadDate: new Date("2025-04-08"),
      uploadSource: "Email"
    },
    aiExtractedData: {
      invoiceNumber: "9106602792",
      supplier: "Coca-Cola Europacific Partners",
      supplierAddress: "Uxbridge Business Park, Sanderson Road, Uxbridge UB8 1DH",
      invoiceDate: new Date("2025-04-08"),
      dueDate: new Date("2025-05-24"),
      totalAmount: 556.69,
      subtotalAmount: 463.91,
      vatAmount: 92.78,
      currency: "GBP",
      accountCode: "5000",
      storeLocation: "Lancaster"
    },
    supplierInfo: {
      id: "sup001",
      name: "Coca-Cola Europacific Partners",
      address: "Uxbridge Business Park, Sanderson Road, Uxbridge UB8 1DH",
      taxId: "GB123456789",
      accountCode: "5000",
      paymentTerms: "NET 30",
      isNew: false,
      confidence: 95
    },
    reviewErrors: [
      {
        id: "err001",
        type: "unknown_account_code",
        title: "Account Code Verification Required",
        description: "AI suggests account code 5000 for beverage supplies but requires confirmation",
        severity: "medium",
        suggestedAction: "Verify correct account code for beverage purchases",
        fieldPath: "accountCode",
        confidence: 75
      }
    ],
    lineItems: [
      {
        id: "item001",
        description: "1.25L NRP X12 COCA-COLA",
        category: "Beverages",
        quantity: 8,
        price: 8.76,
        subtotal: 70.08,
        vatRate: 20,
        vat: 14.02,
        total: 84.10,
        trackingCategory: "Lancaster",
      },
      {
        id: "item002",
        description: "500ML NRP X24 COCA-COLA QR",
        category: "Beverages",
        quantity: 6,
        price: 13.53,
        subtotal: 81.18,
        vatRate: 20,
        vat: 16.24,
        total: 97.42,
        trackingCategory: "Lancaster",
      },
      {
        id: "item003",
        description: "Other beverage products",
        category: "Beverages",
        quantity: 1,
        price: 312.65,
        subtotal: 312.65,
        vatRate: 20,
        vat: 62.53,
        total: 375.18,
        trackingCategory: "Lancaster",
      }
    ],
    requiresJournaling: true,
    notes: "Coca-Cola beverage supply invoice - requires account code verification",
    previewUrl: "/invoice-previews/InvoiceExamples/Coca-Cola_Europacific_Partners_2025-04-08_556.69.pdf",
  },
  {
    id: "inv-002",
    invoiceNumber: "2414",
    company: "Regional Operations Ltd",
    store: "Birmingham",
    source: "Email Upload",
    date: new Date("2025-03-24"),
    dueDate: new Date("2025-04-23"),
    accountCode: "6300",
    status: "Review",
    subtotal: 114.60,
    vatRate: 20,
    vat: 22.92,
    total: 137.52,
    paymentMethod: "Bank Transfer",
    archived: false,
    deleted: false,
    documentType: "Bill",
    uploadedFile: {
      id: "file002",
      name: "Combat_Fire_Limited_2025-03-24_137.52.pdf",
      type: "pdf",
      url: "/invoice-previews/InvoiceExamples/Combat_Fire_Limited_2025-03-24_137.52.pdf",
      size: 215040,
      uploadDate: new Date("2025-03-24"),
      uploadSource: "WhatsApp"
    },
    aiExtractedData: {
      invoiceNumber: "2414",
      supplier: "Combat Fire Limited",
      supplierAddress: "Unit 4, Riverside Industrial Estate, Fazeley, Tamworth B78 3RW",
      invoiceDate: new Date("2025-03-24"),
      dueDate: new Date("2025-04-23"),
      totalAmount: 137.52,
      subtotalAmount: 114.60,
      vatAmount: 22.92,
      currency: "GBP",
      storeLocation: "Birmingham"
    },
    supplierInfo: {
      name: "Combat Fire Limited",
      address: "Unit 4, Riverside Industrial Estate, Fazeley, Tamworth B78 3RW",
      taxId: "GB987654321",
      isNew: true,
      confidence: 88
    },
    reviewErrors: [
      {
        id: "err002",
        type: "new_supplier",
        title: "New Supplier Detected",
        description: "Combat Fire Limited is not in your supplier database",
        severity: "high",
        suggestedAction: "Review and add new supplier to database",
        fieldPath: "supplierInfo",
        confidence: 88
      },
      {
        id: "err003",
        type: "unknown_account_code",
        title: "Account Code Required",
        description: "No account code found for fire safety services",
        severity: "high",
        suggestedAction: "Assign appropriate account code (suggested: 6300 - Maintenance)",
        fieldPath: "accountCode",
        confidence: 60
      }
    ],
    lineItems: [
      {
        id: "item004",
        description: "6 Monthly Fire Alarm Service",
        category: "Maintenance",
        quantity: 1,
        price: 114.60,
        subtotal: 114.60,
        vatRate: 5,
        vat: 5.73,
        total: 120.33,
        trackingCategory: "Birmingham",
      }
    ],
    requiresJournaling: true,
    notes: "Fire safety service invoice - new supplier requires setup",
    previewUrl: "/invoice-previews/InvoiceExamples/Combat_Fire_Limited_2025-03-24_137.52.pdf",
  },

  // PROCESSING STATUS INVOICES
  {
    id: "inv-003",
    invoiceNumber: "INV-2025-001",
    store: "Manchester",
    source: "Email Upload",
    date: new Date("2025-05-07"),
    status: "Processing",
    subtotal: 235.00,
    vatRate: 20,
    vat: 47.00,
    total: 282.00,
    paymentMethod: "Bank Transfer",
    archived: false,
    deleted: false,
    documentType: "Bill",
    uploadedFile: {
      id: "file003",
      name: "Comfort_Cooling_Services_2025-05-07_282.00.pdf",
      type: "pdf",
      url: "/invoice-previews/InvoiceExamples/Comfort_Cooling_Services_2025-05-07_282.00.pdf",
      size: 408576,
      uploadDate: new Date("2025-05-07")
    },
    aiExtractedData: {
      invoiceNumber: "INV-2025-001",
      supplier: "Comfort Cooling Services",
      invoiceDate: new Date("2025-05-07"),
      totalAmount: 282.00,
      currency: "GBP"
    },
    supplierInfo: {
      name: "Comfort Cooling Services",
      isNew: false,
      confidence: 45
    },
    lineItems: [],
    requiresJournaling: false,
    notes: "Currently being processed by AI - extracting line item details",
  },
  {
    id: "inv-004",
    invoiceNumber: "4567",
    store: "Liverpool",
    source: "Email Upload",
    date: new Date("2024-11-26"),
    status: "Processing",
    subtotal: 92.50,
    vatRate: 20,
    vat: 18.50,
    total: 111.00,
    paymentMethod: "Bank Transfer",
    archived: false,
    deleted: false,
    documentType: "Invoice",
    uploadedFile: {
      id: "file004",
      name: "Icon_Engineering_2024-11-26_111.00.pdf",
      type: "pdf",
      url: "/invoice-previews/InvoiceExamples/Icon_Engineering_2024-11-26_111.00.pdf",
      size: 397312,
      uploadDate: new Date("2024-11-26")
    },
    aiExtractedData: {
      invoiceNumber: "4567",
      supplier: "Icon Engineering",
      invoiceDate: new Date("2024-11-26"),
      totalAmount: 111.00,
      currency: "GBP"
    },
    supplierInfo: {
      name: "Icon Engineering",
      isNew: false,
      confidence: 78
    },
    lineItems: [],
    requiresJournaling: false,
    notes: "Currently being processed by AI - low quality scan detected",
  },

  // PROCESSED STATUS INVOICES
  {
    id: "inv-005",
    invoiceNumber: "IG/4290",
    store: "London East",
    source: "Email Upload",
    date: new Date("2023-11-08"),
    status: "Processed",
    subtotal: 3575.00,
    vatRate: 20,
    vat: 715.00,
    total: 4290.00,
    paymentMethod: "Bank Transfer",
    archived: false,
    deleted: false,
    documentType: "Bill",
    uploadedFile: {
      id: "file005",
      name: "Imperial_Green_2023-11-08_4290.00.pdf",
      type: "pdf",
      url: "/invoice-previews/InvoiceExamples/Imperial_Green_2023-11-08_4290.00.pdf",
      size: 34816,
      uploadDate: new Date("2023-11-08")
    },
    aiExtractedData: {
      invoiceNumber: "IG/4290",
      supplier: "Imperial Green",
      supplierAddress: "123 Green Street, London E1 6AN",
      invoiceDate: new Date("2023-11-08"),
      dueDate: new Date("2023-12-08"),
      totalAmount: 4290.00,
      subtotalAmount: 3575.00,
      vatAmount: 715.00,
      currency: "GBP",
      accountCode: "6200",
      storeLocation: "London East"
    },
    supplierInfo: {
      id: "sup005",
      name: "Imperial Green",
      address: "123 Green Street, London E1 6AN",
      taxId: "GB555666777",
      accountCode: "6200",
      paymentTerms: "NET 30",
      isNew: false,
      confidence: 95
    },
    lineItems: [
      {
        id: "item005",
        description: "Landscaping Services",
        category: "Property Maintenance",
        quantity: 1,
        price: 3575.00,
        subtotal: 3575.00,
        vatRate: 20,
        vat: 715.00,
        total: 4290.00,
      }
    ],
    requiresJournaling: true,
    journalEntries: [
      {
        id: "je005",
        account: "6200",
        description: "Property Maintenance",
        debit: 3575.00,
        credit: 0,
      },
      {
        id: "je006",
        account: "1210",
        description: "VAT Reclaimable",
        debit: 715.00,
        credit: 0,
      },
      {
        id: "je007",
        account: "2100",
        description: "Accounts Payable",
        debit: 0,
        credit: 4290.00,
      },
    ],
    notes: "Landscaping services invoice - successfully processed",
    previewUrl: "/invoice-previews/InvoiceExamples/Imperial_Green_2023-11-08_4290.00.pdf",
  },
  {
    id: "inv-006",
    invoiceNumber: "1234",
    store: "Birmingham",
    source: "Email Upload",
    date: new Date("2025-04-06"),
    status: "Processed",
    subtotal: 275.00,
    vatRate: 20,
    vat: 55.00,
    total: 330.00,
    paymentMethod: "Bank Transfer",
    archived: false,
    deleted: false,
    documentType: "Invoice",
    uploadedFile: {
      id: "file006",
      name: "J_C_McCollom_2025-04-06_330.00.pdf",
      type: "pdf",
      url: "/invoice-previews/InvoiceExamples/J_C_McCollom_2025-04-06_330.00.pdf",
      size: 12288,
      uploadDate: new Date("2025-04-06")
    },
    aiExtractedData: {
      invoiceNumber: "1234",
      supplier: "J C McCollom",
      supplierAddress: "45 Industrial Estate, Birmingham B12 0XQ",
      invoiceDate: new Date("2025-04-06"),
      totalAmount: 330.00,
      subtotalAmount: 275.00,
      vatAmount: 55.00,
      currency: "GBP",
      accountCode: "6100",
      storeLocation: "Birmingham"
    },
    supplierInfo: {
      id: "sup006",
      name: "J C McCollom",
      address: "45 Industrial Estate, Birmingham B12 0XQ",
      taxId: "GB444555666",
      accountCode: "6100",
      paymentTerms: "NET 30",
      isNew: false,
      confidence: 92
    },
    lineItems: [
      {
        id: "item006",
        description: "Professional Services",
        category: "Consulting",
        quantity: 1,
        price: 275.00,
        subtotal: 275.00,
        vatRate: 20,
        vat: 55.00,
        total: 330.00,
      }
    ],
    requiresJournaling: true,
    journalEntries: [
      {
        id: "je008",
        account: "6100",
        description: "Professional Services",
        debit: 275.00,
        credit: 0,
      },
      {
        id: "je009",
        account: "1210",
        description: "VAT Reclaimable",
        debit: 55.00,
        credit: 0,
      },
      {
        id: "je010",
        account: "2100",
        description: "Accounts Payable",
        debit: 0,
        credit: 330.00,
      },
    ],
    notes: "Professional services invoice - successfully processed",
    previewUrl: "/invoice-previews/InvoiceExamples/J_C_McCollom_2025-04-06_330.00.pdf",
  },
  {
    id: "inv-007",
    invoiceNumber: "JE-183.30",
    store: "Manchester",
    source: "JustEat Platform",
    date: new Date("2025-04-20"),
    status: "Processed",
    subtotal: 152.75,
    vatRate: 20,
    vat: 30.55,
    total: 183.30,
    paymentMethod: "Platform Settlement",
    archived: false,
    deleted: false,
    documentType: "Invoice",
    uploadedFile: {
      id: "file007",
      name: "Just_Eat_2025-04-20_183.30.png",
      type: "image",
      url: "/invoice-previews/InvoiceExamples/Just_Eat_2025-04-20_183.30.png",
      size: 38912,
      uploadDate: new Date("2025-04-20"),
      uploadSource: "Manual Upload"
    },
    aiExtractedData: {
      invoiceNumber: "JE-183.30",
      supplier: "Just Eat Holdings Ltd",
      invoiceDate: new Date("2025-04-20"),
      totalAmount: 183.30,
      subtotalAmount: 152.75,
      vatAmount: 30.55,
      currency: "GBP",
      accountCode: "4000",
      storeLocation: "Manchester"
    },
    supplierInfo: {
      id: "sup007",
      name: "Just Eat Holdings Ltd",
      address: "Fleet Place House, 2 Fleet Pl, London EC4M 7RF",
      taxId: "GB333444555",
      accountCode: "4000",
      paymentTerms: "Weekly Settlement",
      isNew: false,
      confidence: 95
    },
    lineItems: [
      {
        id: "item007",
        description: "Platform Sales Revenue",
        category: "Sales",
        quantity: 1,
        price: 152.75,
        subtotal: 152.75,
        vatRate: 20,
        vat: 30.55,
        total: 183.30,
      }
    ],
    requiresJournaling: true,
    notes: "JustEat platform sales - successfully processed",
    previewUrl: "/invoice-previews/InvoiceExamples/Just_Eat_2025-04-20_183.30.png",
  },

  // PUBLISHED STATUS INVOICES
  {
    id: "inv-008",
    invoiceNumber: "LUSU-300",
    store: "Lancaster",
    source: "Email Upload",
    date: new Date("2025-04-01"),
    status: "Published",
    subtotal: 250.00,
    vatRate: 20,
    vat: 50.00,
    total: 300.00,
    paymentMethod: "Bank Transfer",
    archived: false,
    deleted: false,
    documentType: "Bill",
    uploadedFile: {
      id: "file008",
      name: "LUSU_General_Account_2025-04-01_300.00.pdf",
      type: "pdf",
      url: "/invoice-previews/InvoiceExamples/LUSU_General_Account_2025-04-01_300.00.pdf",
      size: 5427,
      uploadDate: new Date("2025-04-01")
    },
    aiExtractedData: {
      invoiceNumber: "LUSU-300",
      supplier: "LUSU General Account",
      supplierAddress: "Lancaster University Students' Union, Lancaster LA1 4YW",
      invoiceDate: new Date("2025-04-01"),
      totalAmount: 300.00,
      subtotalAmount: 250.00,
      vatAmount: 50.00,
      currency: "GBP",
      accountCode: "6500",
      storeLocation: "Lancaster"
    },
    supplierInfo: {
      id: "sup008",
      name: "LUSU General Account",
      address: "Lancaster University Students' Union, Lancaster LA1 4YW",
      taxId: "GB666777888",
      accountCode: "6500",
      paymentTerms: "NET 30",
      isNew: false,
      confidence: 98
    },
    lineItems: [
      {
        id: "item008",
        description: "Student Union Services",
        category: "Marketing",
        quantity: 1,
        price: 250.00,
        subtotal: 250.00,
        vatRate: 20,
        vat: 50.00,
        total: 300.00,
      }
    ],
    requiresJournaling: true,
    journalEntries: [
      {
        id: "je011",
        account: "6500",
        description: "Marketing Expenses",
        debit: 250.00,
        credit: 0,
      },
      {
        id: "je012",
        account: "1210",
        description: "VAT Reclaimable",
        debit: 50.00,
        credit: 0,
      },
      {
        id: "je013",
        account: "2100",
        description: "Accounts Payable",
        debit: 0,
        credit: 300.00,
      },
    ],
    notes: "Successfully processed and posted to accounting system",
    previewUrl: "/invoice-previews/InvoiceExamples/LUSU_General_Account_2025-04-01_300.00.pdf",
  },
  {
    id: "inv-009",
    invoiceNumber: "LCC-172.50",
    store: "Lancaster",
    source: "Email Upload",
    date: new Date("2025-04-15"),
    status: "Published",
    subtotal: 143.75,
    vatRate: 20,
    vat: 28.75,
    total: 172.50,
    paymentMethod: "Direct Debit",
    archived: false,
    deleted: false,
    documentType: "Bill",
    uploadedFile: {
      id: "file009",
      name: "Lancaster_City_Council_2025-04-15_172.50.pdf",
      type: "pdf",
      url: "/invoice-previews/InvoiceExamples/Lancaster_City_Council_2025-04-15_172.50.pdf",
      size: 60416,
      uploadDate: new Date("2025-04-15")
    },
    aiExtractedData: {
      invoiceNumber: "LCC-172.50",
      supplier: "Lancaster City Council",
      supplierAddress: "Town Hall, Dalton Square, Lancaster LA1 1PJ",
      invoiceDate: new Date("2025-04-15"),
      totalAmount: 172.50,
      subtotalAmount: 143.75,
      vatAmount: 28.75,
      currency: "GBP",
      accountCode: "6400",
      storeLocation: "Lancaster"
    },
    supplierInfo: {
      id: "sup009",
      name: "Lancaster City Council",
      address: "Town Hall, Dalton Square, Lancaster LA1 1PJ",
      taxId: "GB777888999",
      accountCode: "6400",
      paymentTerms: "NET 30",
      isNew: false,
      confidence: 98
    },
    lineItems: [
      {
        id: "item009",
        description: "Business Rates",
        category: "Utilities",
        quantity: 1,
        price: 143.75,
        subtotal: 143.75,
        vatRate: 20,
        vat: 28.75,
        total: 172.50,
      }
    ],
    requiresJournaling: true,
    journalEntries: [
      {
        id: "je014",
        account: "6400",
        description: "Business Rates",
        debit: 143.75,
        credit: 0,
      },
      {
        id: "je015",
        account: "1210",
        description: "VAT Reclaimable",
        debit: 28.75,
        credit: 0,
      },
      {
        id: "je016",
        account: "2100",
        description: "Accounts Payable",
        debit: 0,
        credit: 172.50,
      },
    ],
    notes: "Successfully processed and posted to accounting system",
    previewUrl: "/invoice-previews/InvoiceExamples/Lancaster_City_Council_2025-04-15_172.50.pdf",
  },
  
  // ADDITIONAL INVOICES - MIXED STATUSES
  {
    id: "inv-010",
    invoiceNumber: "MJC-244.67",
    store: "Birmingham",
    source: "Email Upload",
    date: new Date("2024-11-26"),
    status: "Review",
    subtotal: 203.89,
    vatRate: 20,
    vat: 40.78,
    total: 244.67,
    paymentMethod: "Bank Transfer",
    archived: false,
    deleted: false,
    documentType: "Bill",
    uploadedFile: {
      id: "file010",
      name: "MJ_Catterall_Ltd_2024-11-26_244.67.pdf",
      type: "pdf",
      url: "/invoice-previews/InvoiceExamples/MJ_Catterall_Ltd_2024-11-26_244.67.pdf",
      size: 193536,
      uploadDate: new Date("2024-11-26")
    },
    aiExtractedData: {
      invoiceNumber: "MJC-244.67",
      supplier: "MJ Catterall Ltd",
      supplierAddress: "Industrial Estate, Blackpool FY4 5ER",
      invoiceDate: new Date("2024-11-26"),
      totalAmount: 244.67,
      subtotalAmount: 203.89,
      vatAmount: 40.78,
      currency: "GBP",
      storeLocation: "Birmingham"
    },
    supplierInfo: {
      name: "MJ Catterall Ltd",
      address: "Industrial Estate, Blackpool FY4 5ER",
      taxId: "GB888999000",
      isNew: true,
      confidence: 82
    },
    reviewErrors: [
      {
        id: "err010",
        type: "new_supplier",
        title: "New Supplier Detected",
        description: "MJ Catterall Ltd is not in your supplier database",
        severity: "medium",
        suggestedAction: "Review and add new supplier to database",
        fieldPath: "supplierInfo",
        confidence: 82
      }
    ],
    lineItems: [
      {
        id: "item010",
        description: "Industrial Services",
        category: "Maintenance",
        quantity: 1,
        price: 203.89,
        subtotal: 203.89,
        vatRate: 20,
        vat: 40.78,
        total: 244.67,
      }
    ],
    requiresJournaling: true,
    notes: "New supplier - requires setup and verification",
    previewUrl: "/invoice-previews/InvoiceExamples/MJ_Catterall_Ltd_2024-11-26_244.67.pdf",
  },
  {
    id: "inv-011",
    invoiceNumber: "PCC-463.81",
    store: "Manchester",
    source: "Email Upload",
    date: new Date("2023-11-13"),
    status: "Processed",
    subtotal: 386.51,
    vatRate: 20,
    vat: 77.30,
    total: 463.81,
    paymentMethod: "Direct Debit",
    archived: false,
    deleted: false,
    documentType: "Bill",
    uploadedFile: {
      id: "file011",
      name: "Paragon_Customer_Communications_2023-11-13_463.81.pdf",
      type: "pdf",
      url: "/invoice-previews/InvoiceExamples/Paragon_Customer_Communications_2023-11-13_463.81.pdf",
      size: 81920,
      uploadDate: new Date("2023-11-13")
    },
    aiExtractedData: {
      invoiceNumber: "PCC-463.81",
      supplier: "Paragon Customer Communications",
      supplierAddress: "Paragon House, 2-4 Victoria Street, Windsor SL4 1EN",
      invoiceDate: new Date("2023-11-13"),
      totalAmount: 463.81,
      subtotalAmount: 386.51,
      vatAmount: 77.30,
      currency: "GBP",
      accountCode: "6600",
      storeLocation: "Manchester"
    },
    supplierInfo: {
      id: "sup011",
      name: "Paragon Customer Communications",
      address: "Paragon House, 2-4 Victoria Street, Windsor SL4 1EN",
      taxId: "GB111222333",
      accountCode: "6600",
      paymentTerms: "NET 30",
      isNew: false,
      confidence: 94
    },
    lineItems: [
      {
        id: "item011",
        description: "Communication Services",
        category: "Communications",
        quantity: 1,
        price: 386.51,
        subtotal: 386.51,
        vatRate: 20,
        vat: 77.30,
        total: 463.81,
      }
    ],
    requiresJournaling: true,
    journalEntries: [
      {
        id: "je017",
        account: "6600",
        description: "Communication Expenses",
        debit: 386.51,
        credit: 0,
      },
      {
        id: "je018",
        account: "1210",
        description: "VAT Reclaimable",
        debit: 77.30,
        credit: 0,
      },
      {
        id: "je019",
        account: "2100",
        description: "Accounts Payable",
        debit: 0,
        credit: 463.81,
      },
    ],
    notes: "Communication services - successfully processed",
    previewUrl: "/invoice-previews/InvoiceExamples/Paragon_Customer_Communications_2023-11-13_463.81.pdf",
  },
  {
    id: "inv-012",
    invoiceNumber: "PORT-181.1",
    store: "Liverpool",
    source: "Email Upload",
    date: new Date("2025-05-07"),
    status: "Processing",
    subtotal: 150.92,
    vatRate: 20,
    vat: 30.18,
    total: 181.10,
    paymentMethod: "Bank Transfer",
    archived: false,
    deleted: false,
    documentType: "Invoice",
    uploadedFile: {
      id: "file012",
      name: "Portsmouth_2025-05-07_181.1.pdf",
      type: "pdf",
      url: "/invoice-previews/InvoiceExamples/Portsmouth_2025-05-07_181.1.pdf",
      size: 26624,
      uploadDate: new Date("2025-05-07")
    },
    aiExtractedData: {
      invoiceNumber: "PORT-181.1",
      supplier: "Portsmouth Services",
      invoiceDate: new Date("2025-05-07"),
      totalAmount: 181.10,
      currency: "GBP"
    },
    supplierInfo: {
      name: "Portsmouth Services",
      isNew: false,
      confidence: 65
    },
    lineItems: [],
    requiresJournaling: false,
    notes: "Currently being processed by AI - extracting detailed information",
  },
  {
    id: "inv-013",
    invoiceNumber: "PP-184.80",
    store: "Lancaster",
    source: "Email Upload",
    date: new Date("2025-04-30"),
    status: "Processed",
    subtotal: 154.00,
    vatRate: 20,
    vat: 30.80,
    total: 184.80,
    paymentMethod: "Bank Transfer",
    archived: false,
    deleted: false,
    documentType: "Bill",
    uploadedFile: {
      id: "file013",
      name: "Prudent_Plumbing_2025-04-30_184.80.pdf",
      type: "pdf",
      url: "/invoice-previews/InvoiceExamples/Prudent_Plumbing_2025-04-30_184.80.pdf",
      size: 108544,
      uploadDate: new Date("2025-04-30")
    },
    aiExtractedData: {
      invoiceNumber: "PP-184.80",
      supplier: "Prudent Plumbing",
      supplierAddress: "45 Trade Street, Lancaster LA1 3BX",
      invoiceDate: new Date("2025-04-30"),
      totalAmount: 184.80,
      subtotalAmount: 154.00,
      vatAmount: 30.80,
      currency: "GBP",
      accountCode: "6300",
      storeLocation: "Lancaster"
    },
    supplierInfo: {
      id: "sup013",
      name: "Prudent Plumbing",
      address: "45 Trade Street, Lancaster LA1 3BX",
      taxId: "GB222333444",
      accountCode: "6300",
      paymentTerms: "NET 30",
      isNew: false,
      confidence: 91
    },
    lineItems: [
      {
        id: "item013",
        description: "Plumbing Maintenance",
        category: "Maintenance",
        quantity: 1,
        price: 154.00,
        subtotal: 154.00,
        vatRate: 20,
        vat: 30.80,
        total: 184.80,
      }
    ],
    requiresJournaling: true,
    journalEntries: [
      {
        id: "je020",
        account: "6300",
        description: "Maintenance Expenses",
        debit: 154.00,
        credit: 0,
      },
      {
        id: "je021",
        account: "1210",
        description: "VAT Reclaimable",
        debit: 30.80,
        credit: 0,
      },
      {
        id: "je022",
        account: "2100",
        description: "Accounts Payable",
        debit: 0,
        credit: 184.80,
      },
    ],
    notes: "Plumbing maintenance - successfully processed",
    previewUrl: "/invoice-previews/InvoiceExamples/Prudent_Plumbing_2025-04-30_184.80.pdf",
  },
  {
    id: "inv-014",
    invoiceNumber: "WM-237.98",
    store: "Birmingham",
    source: "Email Upload",
    date: new Date("2025-04-26"),
    status: "Published",
    subtotal: 198.32,
    vatRate: 20,
    vat: 39.66,
    total: 237.98,
    paymentMethod: "Direct Debit",
    archived: false,
    deleted: false,
    documentType: "Bill",
    uploadedFile: {
      id: "file014",
      name: "Wynsdale_Waste_Management_2025-04-26_237.98 (1).pdf",
      type: "pdf",
      url: "/invoice-previews/InvoiceExamples/Wynsdale_Waste_Management_2025-04-26_237.98 (1).pdf",
      size: 45056,
      uploadDate: new Date("2025-04-26")
    },
    aiExtractedData: {
      invoiceNumber: "WM-237.98",
      supplier: "Wynsdale Waste Management",
      supplierAddress: "Waste Management Centre, Industrial Park, Birmingham B45 8RT",
      invoiceDate: new Date("2025-04-26"),
      totalAmount: 237.98,
      subtotalAmount: 198.32,
      vatAmount: 39.66,
      currency: "GBP",
      accountCode: "6400",
      storeLocation: "Birmingham"
    },
    supplierInfo: {
      id: "sup014",
      name: "Wynsdale Waste Management",
      address: "Waste Management Centre, Industrial Park, Birmingham B45 8RT",
      taxId: "GB333444555",
      accountCode: "6400",
      paymentTerms: "NET 30",
      isNew: false,
      confidence: 96
    },
    lineItems: [
      {
        id: "item014",
        description: "Waste Collection Services",
        category: "Utilities",
        quantity: 1,
        price: 198.32,
        subtotal: 198.32,
        vatRate: 20,
        vat: 39.66,
        total: 237.98,
      }
    ],
    requiresJournaling: true,
    journalEntries: [
      {
        id: "je023",
        account: "6400",
        description: "Waste Management",
        debit: 198.32,
        credit: 0,
      },
      {
        id: "je024",
        account: "1210",
        description: "VAT Reclaimable",
        debit: 39.66,
        credit: 0,
      },
      {
        id: "je025",
        account: "2100",
        description: "Accounts Payable",
        debit: 0,
        credit: 237.98,
      },
    ],
    notes: "Successfully processed and posted to accounting system",
    previewUrl: "/invoice-previews/InvoiceExamples/Wynsdale_Waste_Management_2025-04-26_237.98 (1).pdf",
  },
  {
    id: "inv-015",
    invoiceNumber: "WM-312.10",
    store: "Manchester",
    source: "Email Upload",
    date: new Date("2025-04-26"),
    status: "Review",
    subtotal: 260.08,
    vatRate: 20,
    vat: 52.02,
    total: 312.10,
    paymentMethod: "Direct Debit",
    archived: false,
    deleted: false,
    documentType: "Bill",
    uploadedFile: {
      id: "file015",
      name: "Wynsdale_Waste_Management_2025-04-26_312.10.pdf",
      type: "pdf",
      url: "/invoice-previews/InvoiceExamples/Wynsdale_Waste_Management_2025-04-26_312.10.pdf",
      size: 45056,
      uploadDate: new Date("2025-04-26")
    },
    aiExtractedData: {
      invoiceNumber: "WM-312.10",
      supplier: "Wynsdale Waste Management",
      supplierAddress: "Waste Management Centre, Industrial Park, Birmingham B45 8RT",
      invoiceDate: new Date("2025-04-26"),
      totalAmount: 312.10,
      subtotalAmount: 260.08,
      vatAmount: 52.02,
      currency: "GBP",
      accountCode: "6400",
      storeLocation: "Manchester"
    },
    supplierInfo: {
      id: "sup014",
      name: "Wynsdale Waste Management",
      address: "Waste Management Centre, Industrial Park, Birmingham B45 8RT",
      taxId: "GB333444555",
      accountCode: "6400",
      paymentTerms: "NET 30",
      isNew: false,
      confidence: 96
    },
    reviewErrors: [
      {
        id: "err015",
        type: "validation_error",
        title: "Duplicate Service Period",
        description: "This invoice covers the same period as WM-237.98 for Birmingham store",
        severity: "high",
        suggestedAction: "Verify service periods and store assignments",
        confidence: 85
      }
    ],
    lineItems: [
      {
        id: "item015",
        description: "Enhanced Waste Collection",
        category: "Utilities",
        quantity: 1,
        price: 260.08,
        subtotal: 260.08,
        vatRate: 20,
        vat: 52.02,
        total: 312.10,
      }
    ],
    requiresJournaling: true,
    notes: "Requires review - potential duplicate service period",
    previewUrl: "/invoice-previews/InvoiceExamples/Wynsdale_Waste_Management_2025-04-26_312.10.pdf",
  },
  {
    id: "inv-016",
    invoiceNumber: "WM-359.42",
    store: "Liverpool",
    source: "Email Upload",
    date: new Date("2025-04-26"),
    status: "Processing",
    subtotal: 299.52,
    vatRate: 20,
    vat: 59.90,
    total: 359.42,
    paymentMethod: "Direct Debit",
    archived: false,
    deleted: false,
    documentType: "Bill",
    uploadedFile: {
      id: "file016",
      name: "Wynsdale_Waste_Management_2025-04-26_359.42 (1).pdf",
      type: "pdf",
      url: "/invoice-previews/InvoiceExamples/Wynsdale_Waste_Management_2025-04-26_359.42 (1).pdf",
      size: 45056,
      uploadDate: new Date("2025-04-26")
    },
    aiExtractedData: {
      invoiceNumber: "WM-359.42",
      supplier: "Wynsdale Waste Management",
      invoiceDate: new Date("2025-04-26"),
      totalAmount: 359.42,
      currency: "GBP"
    },
    supplierInfo: {
      id: "sup014",
      name: "Wynsdale Waste Management",
      address: "Waste Management Centre, Industrial Park, Birmingham B45 8RT",
      taxId: "GB333444555",
      accountCode: "6400",
      paymentTerms: "NET 30",
      isNew: false,
      confidence: 96
    },
    lineItems: [],
    requiresJournaling: false,
    notes: "Currently being processed by AI - extracting service details",
  },
  {
    id: "inv-017",
    invoiceNumber: "XR-738.00",
    store: "London East",
    source: "Email Upload",
    date: new Date("2025-04-25"),
    status: "Processed",
    subtotal: 615.00,
    vatRate: 20,
    vat: 123.00,
    total: 738.00,
    paymentMethod: "Bank Transfer",
    archived: false,
    deleted: false,
    documentType: "Bill",
    uploadedFile: {
      id: "file017",
      name: "Xpressrefrigeration_2025-04-25_738.00.pdf",
      type: "pdf",
      url: "/invoice-previews/InvoiceExamples/Xpressrefrigeration_2025-04-25_738.00.pdf",
      size: 136192,
      uploadDate: new Date("2025-04-25")
    },
    aiExtractedData: {
      invoiceNumber: "XR-738.00",
      supplier: "Xpress Refrigeration",
      supplierAddress: "Unit 12, Cold Storage Industrial Estate, London E14 9SJ",
      invoiceDate: new Date("2025-04-25"),
      totalAmount: 738.00,
      subtotalAmount: 615.00,
      vatAmount: 123.00,
      currency: "GBP",
      accountCode: "6300",
      storeLocation: "London East"
    },
    supplierInfo: {
      id: "sup017",
      name: "Xpress Refrigeration",
      address: "Unit 12, Cold Storage Industrial Estate, London E14 9SJ",
      taxId: "GB444555666",
      accountCode: "6300",
      paymentTerms: "NET 30",
      isNew: false,
      confidence: 93
    },
    lineItems: [
      {
        id: "item017",
        description: "Refrigeration Maintenance",
        category: "Equipment Maintenance",
        quantity: 1,
        price: 615.00,
        subtotal: 615.00,
        vatRate: 20,
        vat: 123.00,
        total: 738.00,
      }
    ],
    requiresJournaling: true,
    journalEntries: [
      {
        id: "je026",
        account: "6300",
        description: "Equipment Maintenance",
        debit: 615.00,
        credit: 0,
      },
      {
        id: "je027",
        account: "1210",
        description: "VAT Reclaimable",
        debit: 123.00,
        credit: 0,
      },
      {
        id: "je028",
        account: "2100",
        description: "Accounts Payable",
        debit: 0,
        credit: 738.00,
      },
    ],
    notes: "Refrigeration maintenance - successfully processed",
    previewUrl: "/invoice-previews/InvoiceExamples/Xpressrefrigeration_2025-04-25_738.00.pdf",
  },
  {
    id: "inv-018",
    invoiceNumber: "S-28108-01",
    store: "Birmingham",
    source: "System Integration",
    date: new Date("2025-04-27"),
    status: "Published",
    subtotal: 2450.00,
    vatRate: 20,
    vat: 490.00,
    total: 2940.00,
    paymentMethod: "Bank Transfer",
    archived: false,
    deleted: false,
    documentType: "Invoice",
    uploadedFile: {
      id: "file018",
      name: "PRE PROCESSED - CustAccountStatementExt.Report_S-28108-01_27-04-2025.pdf",
      type: "pdf",
      url: "/invoice-previews/InvoiceExamples/PRE PROCESSED - CustAccountStatementExt.Report_S-28108-01_27-04-2025.pdf",
      size: 1363149,
      uploadDate: new Date("2025-04-27")
    },
    aiExtractedData: {
      invoiceNumber: "S-28108-01",
      supplier: "Customer Account Services",
      invoiceDate: new Date("2025-04-27"),
      totalAmount: 2940.00,
      subtotalAmount: 2450.00,
      vatAmount: 490.00,
      currency: "GBP",
      accountCode: "4000",
      storeLocation: "Birmingham"
    },
    supplierInfo: {
      id: "sup018",
      name: "Customer Account Services",
      address: "Pre-processed via system integration",
      accountCode: "4000",
      paymentTerms: "NET 30",
      isNew: false,
      confidence: 98
    },
    lineItems: [
      {
        id: "item018",
        description: "Customer Account Statement",
        category: "Sales Revenue",
        quantity: 1,
        price: 2450.00,
        subtotal: 2450.00,
        vatRate: 20,
        vat: 490.00,
        total: 2940.00,
      }
    ],
    requiresJournaling: true,
    journalEntries: [
      {
        id: "je029",
        account: "4000",
        description: "Sales Revenue",
        debit: 0,
        credit: 2450.00,
      },
      {
        id: "je030",
        account: "2200",
        description: "VAT Payable",
        debit: 0,
        credit: 490.00,
      },
      {
        id: "je031",
        account: "1200",
        description: "Accounts Receivable",
        debit: 2940.00,
        credit: 0,
      },
    ],
    notes: "Pre-processed customer statement - successfully posted",
    previewUrl: "/invoice-previews/InvoiceExamples/PRE PROCESSED - CustAccountStatementExt.Report_S-28108-01_27-04-2025.pdf",
  },
  {
    id: "inv-019",
    invoiceNumber: "S-29098-01",
    store: "Manchester",
    source: "System Integration",
    date: new Date("2025-04-27"),
    status: "Published",
    subtotal: 1875.00,
    vatRate: 20,
    vat: 375.00,
    total: 2250.00,
    paymentMethod: "Bank Transfer",
    archived: false,
    deleted: false,
    documentType: "Invoice",
    uploadedFile: {
      id: "file019",
      name: "PRE PROCESSED - CustAccountStatementExt.Report_S-29098-01_27-04-2025.pdf",
      type: "pdf",
      url: "/invoice-previews/InvoiceExamples/PRE PROCESSED - CustAccountStatementExt.Report_S-29098-01_27-04-2025.pdf",
      size: 1468006,
      uploadDate: new Date("2025-04-27")
    },
    aiExtractedData: {
      invoiceNumber: "S-29098-01",
      supplier: "Customer Account Services",
      invoiceDate: new Date("2025-04-27"),
      totalAmount: 2250.00,
      subtotalAmount: 1875.00,
      vatAmount: 375.00,
      currency: "GBP",
      accountCode: "4000",
      storeLocation: "Manchester"
    },
    supplierInfo: {
      id: "sup018",
      name: "Customer Account Services",
      address: "Pre-processed via system integration",
      accountCode: "4000",
      paymentTerms: "NET 30",
      isNew: false,
      confidence: 98
    },
    lineItems: [
      {
        id: "item019",
        description: "Customer Account Statement",
        category: "Sales Revenue",
        quantity: 1,
        price: 1875.00,
        subtotal: 1875.00,
        vatRate: 20,
        vat: 375.00,
        total: 2250.00,
      }
    ],
    requiresJournaling: true,
    journalEntries: [
      {
        id: "je032",
        account: "4000",
        description: "Sales Revenue",
        debit: 0,
        credit: 1875.00,
      },
      {
        id: "je033",
        account: "2200",
        description: "VAT Payable",
        debit: 0,
        credit: 375.00,
      },
      {
        id: "je034",
        account: "1200",
        description: "Accounts Receivable",
        debit: 2250.00,
        credit: 0,
      },
    ],
    notes: "Pre-processed customer statement - successfully posted",
    previewUrl: "/invoice-previews/InvoiceExamples/PRE PROCESSED - CustAccountStatementExt.Report_S-29098-01_27-04-2025.pdf",
  },
  {
    id: "inv-020",
    invoiceNumber: "S-29108-01",
    store: "Liverpool",
    source: "System Integration",
    date: new Date("2025-04-27"),
    status: "Review",
    subtotal: 3200.00,
    vatRate: 20,
    vat: 640.00,
    total: 3840.00,
    paymentMethod: "Bank Transfer",
    archived: false,
    deleted: false,
    documentType: "Invoice",
    uploadedFile: {
      id: "file020",
      name: "PRE PROCESSED - CustAccountStatementExt.Report_S-29108-01_27-04-2025.pdf",
      type: "pdf",
      url: "/invoice-previews/InvoiceExamples/PRE PROCESSED - CustAccountStatementExt.Report_S-29108-01_27-04-2025.pdf",
      size: 1468006,
      uploadDate: new Date("2025-04-27")
    },
    aiExtractedData: {
      invoiceNumber: "S-29108-01",
      supplier: "Customer Account Services",
      invoiceDate: new Date("2025-04-27"),
      totalAmount: 3840.00,
      subtotalAmount: 3200.00,
      vatAmount: 640.00,
      currency: "GBP",
      accountCode: "4000",
      storeLocation: "Liverpool"
    },
    supplierInfo: {
      id: "sup018",
      name: "Customer Account Services",
      address: "Pre-processed via system integration",
      accountCode: "4000",
      paymentTerms: "NET 30",
      isNew: false,
      confidence: 98
    },
    reviewErrors: [
      {
        id: "err020",
        type: "validation_error",
        title: "High Value Transaction",
        description: "This transaction exceeds the normal range for this store",
        severity: "medium",
        suggestedAction: "Verify transaction details and amounts",
        confidence: 75
      }
    ],
    lineItems: [
      {
        id: "item020",
        description: "Customer Account Statement",
        category: "Sales Revenue",
        quantity: 1,
        price: 3200.00,
        subtotal: 3200.00,
        vatRate: 20,
        vat: 640.00,
        total: 3840.00,
      }
    ],
    requiresJournaling: true,
    notes: "High value transaction - requires verification before posting",
    previewUrl: "/invoice-previews/InvoiceExamples/PRE PROCESSED - CustAccountStatementExt.Report_S-29108-01_27-04-2025.pdf",
  }
];

export default salesInvoices;
